/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a1.db.migration.faridm5;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner; // Import Scanner class for reading input

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in); // Create a Scanner object for reading input

        System.out.println("Enter database name: ");
        String dbName = scanner.nextLine(); // Read user input for database name

        System.out.println("Enter username: ");
        String user = scanner.nextLine(); // Read user input for username

        System.out.println("Enter password: ");
        String password = scanner.nextLine(); // Read user input for password

        // Update the URL to include the user-specified database name
        String url = "jdbc:postgresql://localhost:5432/" + dbName; // Adjusted to include dbName

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            System.out.println("Connected to PostgreSQL database!");

            // Create a statement
            try (Statement statement = connection.createStatement()) {
                // Execute a query
                try (ResultSet resultSet = statement.executeQuery("SELECT * FROM test_table")) {
                    // Process the result set
                    while (resultSet.next()) {
                        System.out.println("Column 1: " + resultSet.getString(1));
                        System.out.println("Column 2: " + resultSet.getString(2));
                        // Add more columns as needed
                    }
                }
            }
        } catch (SQLException e) {
            System.err.println("Database connection error: " + e.getMessage());
        } finally {
            scanner.close(); // Close the scanner
        }
    }
}
